# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SHPM
                                 A QGIS plugin
 Interpolation profils lit mineurs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-14
        copyright            : (C) 2022 by Manuel Collongues
        email                : manuel.collongues@cerema.fr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SHPM class from file SHPM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .interpolation_shpm import SHPM
    return SHPM(iface)
