# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SHPM
                                 A QGIS plugin
 Interpolation profils lit mineurs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-14
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Manuel Collongues
        email                : manuel.collongues@cerema.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import QgsProject, QgsVectorLayer, QgsRasterLayer

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .interpolation_shpm_dialog import SHPMDialog
import os.path


class SHPM:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SHPM_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Interpolation SHPM')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('SHPM', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/interpolation_shpm/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Interpolation SHPM'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def select_rive_gauche(self):
        filename_rg, _filter = QFileDialog.getOpenFileName(self.dlg, "Select output file", "", "Shapefile (*.shp)")
        self.dlg.lineshp_rg.setText(filename_rg)
        if not filename_rg or filename_rg == "":
            return
        riveGauche = QgsVectorLayer(filename_rg, "Rive gauche", 'ogr')
        if not riveGauche or not riveGauche.isValid():
            QMessageBox.warning(self.iface.mainWindow(), "Echec", "Le fichier \"%s\" n’est pas reconnu par QGis."% filename_rg.replace('/', os.sep))
            return
        QgsProject.instance().addMapLayer(riveGauche)

    def select_rive_droite(self):
        filename_rd, _filter = QFileDialog.getOpenFileName(self.dlg, "Select output file", "", "Shapefile (*.shp)")
        self.dlg.lineshp_rd.setText(filename_rd)
        if not filename_rd or filename_rd == "":
            return
        riveDroite = QgsVectorLayer(filename_rd, "Rive droite", 'ogr')
        if not riveDroite or not riveDroite.isValid():
            QMessageBox.warning(self.iface.mainWindow(), "Echec", "Le fichier \"%s\" n’est pas reconnu par QGis."% filename_rd.replace('/', os.sep))
            return
        QgsProject.instance().addMapLayer(riveDroite)

    def select_lidar(self):
        filename_lidar, _filter = QFileDialog.getOpenFileName(self.dlg, "Select output file", "", "GeoTIFF (*.tif *tiff *TIF *TIFF)")
        self.dlg.line_raster_lidar.setText(filename_lidar)
        if not filename_lidar or filename_lidar == "":
            return
        lidar_interpolation = QgsRasterLayer(filename_lidar, "SRTM layer name")
        if not lidar_interpolation or not lidar_interpolation.isValid():
            QMessageBox.warning(self.iface.mainWindow(), "Echec", "Le fichier \"%s\" n’est pas reconnu par QGis."% filename_lidar.replace('/', os.sep))
            return
        QgsProject.instance().addMapLayer(lidar_interpolation)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&Interpolation SHPM'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = SHPMDialog()
            self.dlg.pushshp_rivg.clicked.connect(self.select_rive_gauche)
            self.dlg.pushshp_rivd.clicked.connect(self.select_rive_droite)
            self.dlg.push_raster_lidar.clicked.connect(self.select_lidar)

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            pass
