# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\manuel.collongues\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\interpolation_shpm\interpolation_shpm_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SHPMDialogBase(object):
    def setupUi(self, SHPMDialogBase):
        SHPMDialogBase.setObjectName("SHPMDialogBase")
        SHPMDialogBase.resize(698, 478)
        self.button_box = QtWidgets.QDialogButtonBox(SHPMDialogBase)
        self.button_box.setGeometry(QtCore.QRect(310, 420, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.pushshp_rivg = QtWidgets.QPushButton(SHPMDialogBase)
        self.pushshp_rivg.setGeometry(QtCore.QRect(570, 90, 41, 23))
        self.pushshp_rivg.setObjectName("pushshp_rivg")
        self.lineshp_rg = QtWidgets.QLineEdit(SHPMDialogBase)
        self.lineshp_rg.setGeometry(QtCore.QRect(230, 90, 321, 20))
        self.lineshp_rg.setObjectName("lineshp_rg")
        self.label = QtWidgets.QLabel(SHPMDialogBase)
        self.label.setGeometry(QtCore.QRect(70, 90, 161, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(SHPMDialogBase)
        self.label_2.setGeometry(QtCore.QRect(70, 130, 151, 16))
        self.label_2.setObjectName("label_2")
        self.pushshp_rivd = QtWidgets.QPushButton(SHPMDialogBase)
        self.pushshp_rivd.setGeometry(QtCore.QRect(570, 130, 41, 23))
        self.pushshp_rivd.setObjectName("pushshp_rivd")
        self.lineshp_rd = QtWidgets.QLineEdit(SHPMDialogBase)
        self.lineshp_rd.setGeometry(QtCore.QRect(230, 130, 321, 20))
        self.lineshp_rd.setObjectName("lineshp_rd")
        self.label_3 = QtWidgets.QLabel(SHPMDialogBase)
        self.label_3.setGeometry(QtCore.QRect(70, 170, 151, 16))
        self.label_3.setObjectName("label_3")
        self.line_raster_lidar = QtWidgets.QLineEdit(SHPMDialogBase)
        self.line_raster_lidar.setGeometry(QtCore.QRect(230, 170, 321, 20))
        self.line_raster_lidar.setObjectName("line_raster_lidar")
        self.push_raster_lidar = QtWidgets.QPushButton(SHPMDialogBase)
        self.push_raster_lidar.setGeometry(QtCore.QRect(570, 170, 41, 23))
        self.push_raster_lidar.setObjectName("push_raster_lidar")

        self.retranslateUi(SHPMDialogBase)
        self.button_box.accepted.connect(SHPMDialogBase.accept)
        self.button_box.rejected.connect(SHPMDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(SHPMDialogBase)

    def retranslateUi(self, SHPMDialogBase):
        _translate = QtCore.QCoreApplication.translate
        SHPMDialogBase.setWindowTitle(_translate("SHPMDialogBase", "Interpolation SHPM"))
        self.pushshp_rivg.setText(_translate("SHPMDialogBase", "..."))
        self.label.setText(_translate("SHPMDialogBase", "Sélectionner shape rive gauche"))
        self.label_2.setText(_translate("SHPMDialogBase", "Sélectionner shape rive droite"))
        self.pushshp_rivd.setText(_translate("SHPMDialogBase", "..."))
        self.label_3.setText(_translate("SHPMDialogBase", "Sélectionner LIDAR"))
        self.push_raster_lidar.setText(_translate("SHPMDialogBase", "..."))
